<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class AdditionalUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            ['first_name' => 'Sumaia', 'last_name' => 'Ahmadillaeva'],
            ['first_name' => 'Souly', 'last_name' => 'Ang'],
            ['first_name' => 'Ninaca', 'last_name' => 'Ben'],
            ['first_name' => 'Finance', 'last_name' => 'Bin'],
            ['first_name' => 'Mey Mey', 'last_name' => 'Bo'],
            ['first_name' => 'Meychhing', 'last_name' => 'Bou'],
            ['first_name' => 'Meyching', 'last_name' => 'Bou'],
            ['first_name' => 'Jame', 'last_name' => 'Brownlie'],
            ['first_name' => 'Dararith', 'last_name' => 'Bun'],
            ['first_name' => 'Chanvecheka', 'last_name' => 'Bunny'],
            ['first_name' => 'Tieu Yen', 'last_name' => 'Cao'],
            ['first_name' => 'Sokunkanha', 'last_name' => 'Chamroeun'],
            ['first_name' => 'Bengkhong', 'last_name' => 'Chan'],
            // Skip 'Chealinh Chan' since it was in the original seed
            ['first_name' => 'Chey Makara', 'last_name' => 'Chan'],
            ['first_name' => 'Joel', 'last_name' => 'Chan'],
            ['first_name' => 'Molisa', 'last_name' => 'Chan'],
            ['first_name' => 'Narith', 'last_name' => 'Chan'],
            ['first_name' => 'Sreytep', 'last_name' => 'Chan'],
            ['first_name' => 'Tithnisa', 'last_name' => 'Chap'],
            ['first_name' => 'Chan Sophallika', 'last_name' => 'Chea'],
            ['first_name' => 'Kanika', 'last_name' => 'Chea'],
            ['first_name' => 'Leakna', 'last_name' => 'Chea'],
            ['first_name' => 'Meng', 'last_name' => 'Chea'],
            ['first_name' => 'Socheata', 'last_name' => 'Chea'],
            ['first_name' => 'Soksothearith', 'last_name' => 'Chea'],
            ['first_name' => 'Sovanlida', 'last_name' => 'Chea'],
            ['first_name' => 'Liza', 'last_name' => 'Cheat'],
            ['first_name' => 'Panha Pich', 'last_name' => 'Cheng'],
            ['first_name' => 'Malain', 'last_name' => 'Chep'],
            ['first_name' => 'Panhavortey', 'last_name' => 'Chhay'],
            ['first_name' => 'Sorphy', 'last_name' => 'Chhay'],
            ['first_name' => 'Siheng', 'last_name' => 'Chheang'],
            ['first_name' => 'Heng Heng', 'last_name' => 'Chhim'],
            ['first_name' => 'Puthyrith', 'last_name' => 'Chhin'],
            ['first_name' => 'Sorineath', 'last_name' => 'Chhok'],
            ['first_name' => 'Piseth', 'last_name' => 'Chhom'],
            ['first_name' => 'Sovannara', 'last_name' => 'Chhorn'],
            ['first_name' => 'Soklin', 'last_name' => 'Chhoueng'],
            ['first_name' => 'Eaveley', 'last_name' => 'Chhour'],
            ['first_name' => 'Somnang', 'last_name' => 'Chhum'],
            ['first_name' => 'Sokuntevin', 'last_name' => 'Chhy'],
            ['first_name' => 'Sambath Vathana', 'last_name' => 'Chi'],
            ['first_name' => 'Taingleng', 'last_name' => 'Chi'],
            ['first_name' => 'Sokkanha', 'last_name' => 'Chim'],
            ['first_name' => 'Vinly', 'last_name' => 'Chim'],
            ['first_name' => 'Jengkimhuy', 'last_name' => 'Chin'],
            ['first_name' => 'Lynol', 'last_name' => 'Chiv'],
            ['first_name' => 'Rithyvong', 'last_name' => 'Chorn Samit'],
            ['first_name' => 'Nisa', 'last_name' => 'Chot'],
            ['first_name' => 'Chansreyheng', 'last_name' => 'Chou'],
            ['first_name' => 'Kaknika', 'last_name' => 'Chun'],
            ['first_name' => 'Juna', 'last_name' => 'Darith'],
            ['first_name' => 'Sophana', 'last_name' => 'Dim'],
            ['first_name' => 'Norakvannada', 'last_name' => 'Din'],
            ['first_name' => 'Beatrice', 'last_name' => 'Doran'],
            ['first_name' => 'Keo', 'last_name' => 'Duong'],
            ['first_name' => 'Muylim', 'last_name' => 'Dy'],
            ['first_name' => 'Kim Eng', 'last_name' => 'Ea'],
            ['first_name' => 'Kimchhay', 'last_name' => 'Ea'],
            // Skip 'Sodano Ean' as it was in the original seed
            ['first_name' => 'Khevin', 'last_name' => 'Eang'],
            ['first_name' => 'Kimkhun', 'last_name' => 'Eang'],
            // Skip 'Panharoth Ear' as it was in the original seed
            ['first_name' => 'Socheath', 'last_name' => 'Ek'],
            // Skip 'Chanrithy Em' as it was in the original seed
            ['first_name' => 'Sokrattanakbot', 'last_name' => 'Em'],
            ['first_name' => 'Gechleang', 'last_name' => 'En'],
            ['first_name' => 'Davin', 'last_name' => 'Eng'],
            ['first_name' => 'Somean', 'last_name' => 'Eng'],
            ['first_name' => 'Aben', 'last_name' => 'Hak'],
            ['first_name' => 'Sreymey', 'last_name' => 'Hak'],
            ['first_name' => 'Chomroenboth', 'last_name' => 'Hang'],
            ['first_name' => 'Keangchhay', 'last_name' => 'Hang'],
            ['first_name' => 'Sophanaroth', 'last_name' => 'Hang'],
            ['first_name' => 'Manika', 'last_name' => 'Hean'],
            ['first_name' => 'Vattana', 'last_name' => 'Hean'],
            ['first_name' => 'Kimsay', 'last_name' => 'Heap'],
            ['first_name' => 'Khifong', 'last_name' => 'Heng'],
            ['first_name' => 'Pechhong', 'last_name' => 'Heng'],
            ['first_name' => 'Sokesey', 'last_name' => 'Heng'],
            ['first_name' => 'Piththonin', 'last_name' => 'Hengpan'],
            ['first_name' => 'Chanmakara', 'last_name' => 'Heun'],
            ['first_name' => 'Aphitey', 'last_name' => 'Ho'],
            ['first_name' => 'Kasong', 'last_name' => 'Ho'],
            ['first_name' => 'Kimban', 'last_name' => 'Ho'],
            ['first_name' => 'Phouy Y', 'last_name' => 'Hok'],
            ['first_name' => 'Pysey', 'last_name' => 'Hok'],
            ['first_name' => 'Mignlong', 'last_name' => 'Hong'],
            ['first_name' => 'Muygech', 'last_name' => 'Hong'],
            ['first_name' => 'Manil', 'last_name' => 'Hor'],
            // Skip 'Sothearith Horn' as it was in the original seed
            ['first_name' => 'Sengsokyouy', 'last_name' => 'Houn'],
            ['first_name' => 'Kimleng', 'last_name' => 'Hout'],
            ['first_name' => 'Bun Long', 'last_name' => 'Hun'],
            ['first_name' => 'Mengcheu', 'last_name' => 'Huong'],
            ['first_name' => 'Kakada', 'last_name' => 'Huot'],
            // Skip 'Sonita Ieng' as it was in the original seed
            ['first_name' => 'Kimhak', 'last_name' => 'Im'],
            ['first_name' => 'Sopheakneath', 'last_name' => 'Ing'],
            ['first_name' => 'Abdulmukhsin', 'last_name' => 'Ismailov'],
            ['first_name' => 'Yusvorthiny', 'last_name' => 'Kak'],
            ['first_name' => 'Kimsan', 'last_name' => 'Kangloem'],
            ['first_name' => 'Boulyheng', 'last_name' => 'Kao'],
            ['first_name' => 'Vannaro', 'last_name' => 'Kao'],
            ['first_name' => 'Raksamonita', 'last_name' => 'Kea'],
            ['first_name' => 'Thaihour', 'last_name' => 'Kean'],
            ['first_name' => 'Rongrithy', 'last_name' => 'Kemchean'],
            ['first_name' => 'Hengly', 'last_name' => 'Kheang'],
            ['first_name' => 'Zorngtin', 'last_name' => 'Kheang'],
            ['first_name' => 'Babera', 'last_name' => 'Kheankeo'],
            ['first_name' => 'Vichera', 'last_name' => 'Khem'],
            ['first_name' => 'Sovathpanha', 'last_name' => 'Khen'],
            ['first_name' => 'Vydanut', 'last_name' => 'Kheng'],
            ['first_name' => 'Chinmuni', 'last_name' => 'Khin'],
            ['first_name' => 'Sambathvirakboth', 'last_name' => 'Khon'],
            ['first_name' => 'Suntry', 'last_name' => 'Khou'],
            ['first_name' => 'Hunlean', 'last_name' => 'Kim'],
            ['first_name' => 'Kuntito', 'last_name' => 'Kim'],
            ['first_name' => 'Pheng An', 'last_name' => 'Kim'],
            ['first_name' => 'Puthy', 'last_name' => 'Kim'],
            ['first_name' => 'So Nita', 'last_name' => 'Kim'],
            ['first_name' => 'Visoth', 'last_name' => 'Kim'],
            ['first_name' => 'Winsokhaborey', 'last_name' => 'Kim'],
            ['first_name' => 'Yiyi', 'last_name' => 'Kim'],
            ['first_name' => 'Chansreymey', 'last_name' => 'Kin'],
            // Skip 'Honglee Kin' as it was in the original seed
            ['first_name' => 'Sokhour', 'last_name' => 'Kin'],
            ['first_name' => 'Thida', 'last_name' => 'Kin'],
            ['first_name' => 'Soly', 'last_name' => 'Koem'],
            ['first_name' => 'Misel', 'last_name' => 'Koksal'],
            ['first_name' => 'Dolla', 'last_name' => 'Kong'],
            ['first_name' => 'Puthiroth', 'last_name' => 'Kong'],
            ['first_name' => 'Rothrina', 'last_name' => 'Kong'],
            // Skip 'Tisamnop Kong' as it was in the original seed
            ['first_name' => 'Bunhengsokleap', 'last_name' => 'Kor'],
            ['first_name' => 'Sophayuc', 'last_name' => 'Kosal'],
            ['first_name' => 'Vengtheang', 'last_name' => 'Kouch'],
            // Skip 'Bunnarong Kreang' as it was in the original seed
            // Skip 'Sokseyha Kruy' as it was in the original seed
            ['first_name' => 'Sengvisal', 'last_name' => 'Kuoch'],
            ['first_name' => 'Norin', 'last_name' => 'Kuy'],
            ['first_name' => 'Nimulkanika', 'last_name' => 'Ky'],
            ['first_name' => 'Socheata', 'last_name' => 'Lam'],
            ['first_name' => 'Roeunrya', 'last_name' => 'Lan'],
            ['first_name' => 'Sovann', 'last_name' => 'Lay'],
            ['first_name' => 'Thon', 'last_name' => 'Lay'],
            ['first_name' => 'Ravy', 'last_name' => 'Leat'],
            ['first_name' => 'Poray', 'last_name' => 'Lee'],
            ['first_name' => 'Povisoth', 'last_name' => 'Lee'],
            ['first_name' => 'Dareach', 'last_name' => 'Lim'],
            ['first_name' => 'Leaderna', 'last_name' => 'Lim'],
            ['first_name' => 'Leakhena', 'last_name' => 'Lim'],
            ['first_name' => 'Mengkuy', 'last_name' => 'Lim'],
            ['first_name' => 'Phary', 'last_name' => 'Lim'],
            ['first_name' => 'Povtharith', 'last_name' => 'Lim'],
            ['first_name' => 'Tineo', 'last_name' => 'Lim'],
            ['first_name' => 'Vouchleang', 'last_name' => 'Lim'],
            ['first_name' => 'Daneth', 'last_name' => 'Loeung'],
            ['first_name' => 'Henglong', 'last_name' => 'Loeung'],
            ['first_name' => 'Unharangsey', 'last_name' => 'Lonn'],
            ['first_name' => 'Roza', 'last_name' => 'Lor'],
            // Skip 'Sreylin Loun' as it was in the original seed
            ['first_name' => 'Ehong', 'last_name' => 'Lout'],
            // Skip 'Stephanie Lu' as it was in the original seed
            ['first_name' => 'Chanvorleak', 'last_name' => 'Lun'],
            // Skip 'Vanhong Luy' as it was in the original seed
            ['first_name' => 'Bolin', 'last_name' => 'Ly'],
            ['first_name' => 'Chanthea', 'last_name' => 'Ly'],
            ['first_name' => 'Menglong', 'last_name' => 'Ly'],
            ['first_name' => 'Monirachana', 'last_name' => 'Ly'],
            ['first_name' => 'Monyrath', 'last_name' => 'Ly'],
            ['first_name' => 'Pheng An', 'last_name' => 'Ly'],
            ['first_name' => 'Serey Vathanak', 'last_name' => 'Ly'],
            ['first_name' => 'Sokleap', 'last_name' => 'Ly'],
            ['first_name' => 'Vouch E', 'last_name' => 'Ly'],
            ['first_name' => 'Socheat', 'last_name' => 'Ma'],
            ['first_name' => 'Panhanoreak', 'last_name' => 'Mak'],
            ['first_name' => 'Sengsereyroth', 'last_name' => 'Mao'],
            ['first_name' => 'Socheata', 'last_name' => 'Mao'],
            ['first_name' => 'Penh Sunmey', 'last_name' => 'Martin'],
            ['first_name' => 'Rithy', 'last_name' => 'Mean'],
            ['first_name' => 'Alvindelacruz', 'last_name' => 'Meas'],
            ['first_name' => 'Soma', 'last_name' => 'Meas'],
            ['first_name' => 'Moniratanak', 'last_name' => 'Men'],
            ['first_name' => 'Votey', 'last_name' => 'Mengphan'],
            ['first_name' => 'Sokpanhanita', 'last_name' => 'Met'],
            ['first_name' => 'Punlork', 'last_name' => 'Mey'],
            ['first_name' => 'Chankanika', 'last_name' => 'Min'],
            ['first_name' => 'Seangly', 'last_name' => 'Moeun'],
            ['first_name' => 'Kunthu', 'last_name' => 'Muny'],
            ['first_name' => 'Vitou', 'last_name' => 'Muy'],
            ['first_name' => 'Zuhro', 'last_name' => 'Nabotova'],
            ['first_name' => 'Danin', 'last_name' => 'Nan'],
            ['first_name' => 'Niramonita', 'last_name' => 'Neang'],
            // Skip 'Kimlong Neng' as it was in the original seed
            ['first_name' => 'Sothearak', 'last_name' => 'Ngorn'],
            ['first_name' => 'Seangheng', 'last_name' => 'Ngov'],
            ['first_name' => 'Techheng', 'last_name' => 'Ngy'],
            ['first_name' => 'Kimheng', 'last_name' => 'Nhoeb'],
            ['first_name' => 'Vongvimean', 'last_name' => 'Nhoek'],
            ['first_name' => 'Vannyden', 'last_name' => 'Nim'],
            ['first_name' => 'Tonghaing', 'last_name' => 'Nob'],
            ['first_name' => 'Chan Sokliep', 'last_name' => 'Nop'],
            ['first_name' => 'Sokream', 'last_name' => 'Norn'],
            ['first_name' => 'Monykanhchana', 'last_name' => 'Nuth'],
            ['first_name' => 'Vattanac', 'last_name' => 'Ny'],
            ['first_name' => 'Seavmuy', 'last_name' => 'Oeng'],
            ['first_name' => 'Sinhhout', 'last_name' => 'Oeng'],
            ['first_name' => 'Bunsovannreach', 'last_name' => 'Ou'],
            ['first_name' => 'Solyna', 'last_name' => 'Ouch'],
            ['first_name' => 'Sovanvathanakreaksmey', 'last_name' => 'Oum'],
            ['first_name' => 'Akphecheata', 'last_name' => 'Oumpreok'],
            ['first_name' => 'Tongsovanmary', 'last_name' => 'Oung'],
            ['first_name' => 'Senghout', 'last_name' => 'Peng'],
            ['first_name' => 'Rattanakpong', 'last_name' => 'Pha'],
            ['first_name' => 'Roza', 'last_name' => 'Phal'],
            ['first_name' => 'Vichnea', 'last_name' => 'Phal'],
            ['first_name' => 'Seavlong', 'last_name' => 'Phally'],
            ['first_name' => 'Chheavlin', 'last_name' => 'Phan'],
            ['first_name' => 'Leangheak', 'last_name' => 'Phan'],
            ['first_name' => 'Sokundawin', 'last_name' => 'Phat'],
            ['first_name' => 'Iychhean', 'last_name' => 'Pheang'],
            ['first_name' => 'Sotheary', 'last_name' => 'Phoem'],
            ['first_name' => 'Sokpheng', 'last_name' => 'Phon'],
            ['first_name' => 'Heang Piv', 'last_name' => 'Phour'],
            ['first_name' => 'Ro En', 'last_name' => 'Phuong'],
            // Skip 'Sereywattana Pich' as it was in the original seed
            ['first_name' => 'Pichphalla', 'last_name' => 'Poch'],
            ['first_name' => 'Phandavin', 'last_name' => 'Por'],
            ['first_name' => 'Sreygech', 'last_name' => 'Pov'],
            ['first_name' => 'Sovanpanha', 'last_name' => 'Puth'],
            ['first_name' => 'Lina', 'last_name' => 'Raksmey'],
            ['first_name' => 'Vitou', 'last_name' => 'Raksmey'],
            // Skip 'Saingiy Rat' as it was in the original seed
            ['first_name' => 'Rath Boramey', 'last_name' => 'Ren'],
            ['first_name' => 'Sovandara', 'last_name' => 'Rith'],
            ['first_name' => 'Someta', 'last_name' => 'Rithy'],
            ['first_name' => 'Manisa', 'last_name' => 'Ros'],
            ['first_name' => 'Sotheary', 'last_name' => 'Ros'],
            ['first_name' => 'Marady', 'last_name' => 'Rou'],
            ['first_name' => 'Phirun', 'last_name' => 'Roum'],
            ['first_name' => 'Chanbormey', 'last_name' => 'Rous'],
            ['first_name' => 'Senghoung', 'last_name' => 'Rov'],
            ['first_name' => 'Rithy', 'last_name' => 'Run'],
            ['first_name' => 'Sophearith', 'last_name' => 'Ry'],
            ['first_name' => 'Vattana', 'last_name' => 'Ry'],
            ['first_name' => 'Thavrakbondith', 'last_name' => 'Sam'],
            // Skip 'Manin Samat' as it was in the original seed
            ['first_name' => 'Sreychou', 'last_name' => 'Samnang'],
            ['first_name' => 'Brakod', 'last_name' => 'Samrech'],
            ['first_name' => 'Dyvannda', 'last_name' => 'San'],
            ['first_name' => 'Meng Sreang', 'last_name' => 'San'],
            ['first_name' => 'Sreypov', 'last_name' => 'Sang'],
            ['first_name' => 'Visal', 'last_name' => 'Sang'],
            ['first_name' => 'Sathyadavid', 'last_name' => 'Sao'],
            ['first_name' => 'Samretrita', 'last_name' => 'Sar'],
            ['first_name' => 'Vichara', 'last_name' => 'Sara'],
            ['first_name' => 'David', 'last_name' => 'Sary'],
            ['first_name' => 'Sokneasa', 'last_name' => 'Sat'],
            // Skip 'Chanleap Say' as it was in the original seed
            ['first_name' => 'Pinasa', 'last_name' => 'Se'],
            ['first_name' => 'Lychhay', 'last_name' => 'Sean'],
            // Skip 'Puthisom Sear' as it was in the original seed
            ['first_name' => 'Visal', 'last_name' => 'Sek'],
            ['first_name' => 'Dyvathiny', 'last_name' => 'Sem'],
            ['first_name' => 'Ai Ei', 'last_name' => 'Seng'],
            ['first_name' => 'Kimmean', 'last_name' => 'Seng'],
            ['first_name' => 'Ratanak Pich', 'last_name' => 'Seng'],
            ['first_name' => 'Virakboth', 'last_name' => 'Seng'],
            ['first_name' => 'Muslim', 'last_name' => 'Shafii'],
            ['first_name' => 'Kibriyo', 'last_name' => 'Shomirzoeva'],
            ['first_name' => 'Virakserey', 'last_name' => 'Siek'],
            ['first_name' => 'Lypheng', 'last_name' => 'Sim'],
            ['first_name' => 'Sonita', 'last_name' => 'Sim'],
            ['first_name' => 'Seav I', 'last_name' => 'Sin'],
            ['first_name' => 'Sophea', 'last_name' => 'Sinat'],
            ['first_name' => 'Pisdar', 'last_name' => 'Sing'],
            ['first_name' => 'Sophanyka', 'last_name' => 'Sith'],
            ['first_name' => 'Rithliza', 'last_name' => 'So'],
            ['first_name' => 'Savina', 'last_name' => 'Soeun'],
            ['first_name' => 'Kim I', 'last_name' => 'Sok'],
            ['first_name' => 'Kimsong', 'last_name' => 'Sok'],
            ['first_name' => 'Porchou', 'last_name' => 'Sok'],
            ['first_name' => 'Rady', 'last_name' => 'Sok'],
            // Skip 'Siriphort Sokhun' as it was in the original seed
            ['first_name' => 'Meng Billionaire', 'last_name' => 'Sokun'],
            ['first_name' => 'Meanhout', 'last_name' => 'Son'],
            // Skip 'Rothtisa Song' as it was in the original seed
            ['first_name' => 'Sodane', 'last_name' => 'Song'],
            // Skip 'Uylong Song' as it was in the original seed
            ['first_name' => 'Vissavatey', 'last_name' => 'Sophana'],
            ['first_name' => 'Maridy', 'last_name' => 'Sophat'],
            ['first_name' => 'Kanika', 'last_name' => 'Sopheap'],
            ['first_name' => 'Kimsuong', 'last_name' => 'Sor'],
            ['first_name' => 'Seangheng', 'last_name' => 'Sor'],
            ['first_name' => 'Sonita', 'last_name' => 'Sor'],
            ['first_name' => 'Sophealeak', 'last_name' => 'Sor'],
            ['first_name' => 'Somnang', 'last_name' => 'Sorn'],
            ['first_name' => 'Setiyuth', 'last_name' => 'Sothea'],
            ['first_name' => 'You Ee', 'last_name' => 'Sourtoeung'],
            ['first_name' => 'Samphors', 'last_name' => 'Sous'],
            // Skip 'Theanaraksa Srorn' as it was in the original seed
            ['first_name' => 'Kimsan', 'last_name' => 'Srunsarath'],
            ['first_name' => 'Sampheasa', 'last_name' => 'Sun'],
            ['first_name' => 'Soksambo', 'last_name' => 'Sun'],
            ['first_name' => 'Taingkea', 'last_name' => 'Suy'],
            ['first_name' => 'Raksa', 'last_name' => 'Svay'],
            ['first_name' => 'Kok An', 'last_name' => 'Taing'],
            ['first_name' => 'Mengchhay', 'last_name' => 'Taing'],
            ['first_name' => 'Muy Lay', 'last_name' => 'Taing'],
            ['first_name' => 'Songhy', 'last_name' => 'Taing'],
            ['first_name' => 'Cheangxing', 'last_name' => 'Tan'],
            ['first_name' => 'Dalyna', 'last_name' => 'Tan'],
            ['first_name' => 'Kimhuoy', 'last_name' => 'Tan'],
            ['first_name' => 'Renu', 'last_name' => 'Tan'],
            ['first_name' => 'Bunlong', 'last_name' => 'Tang'],
            ['first_name' => 'Seavlong', 'last_name' => 'Tang'],
            ['first_name' => 'Sieping', 'last_name' => 'Tang'],
            ['first_name' => 'Nita', 'last_name' => 'Tay'],
            ['first_name' => 'Chhor Dav', 'last_name' => 'Te'],
            ['first_name' => 'Phalborith', 'last_name' => 'Teang'],
            ['first_name' => 'Bonitapravid', 'last_name' => 'Tem'],
            // Skip 'Seakpanhaseth Teng' as it was in the original seed
            ['first_name' => 'Sokchoeng', 'last_name' => 'Teng'],
            ['first_name' => 'Solita', 'last_name' => 'Thearos'],
            ['first_name' => 'Madina', 'last_name' => 'Theng'],
            ['first_name' => 'Singthay', 'last_name' => 'Theng'],
            ['first_name' => 'Sogech', 'last_name' => 'Theng'],
            ['first_name' => 'Sovira', 'last_name' => 'Theng'],
            ['first_name' => 'Chhainarin', 'last_name' => 'Thoeun'],
            ['first_name' => 'Nalin', 'last_name' => 'Thon'],
            // Skip 'Pagnavitou Thong' as it was in the original seed
            ['first_name' => 'Sereyboth', 'last_name' => 'Thorn'],
            ['first_name' => 'Sereyvath', 'last_name' => 'Thorn'],
            ['first_name' => 'Sotheara', 'last_name' => 'Thun'],
            ['first_name' => 'Somanea', 'last_name' => 'Thya'],
            ['first_name' => 'Sambatbunlong', 'last_name' => 'Tim'],
            ['first_name' => 'Vutha', 'last_name' => 'Ting'],
            ['first_name' => 'Vanelite', 'last_name' => 'Tith'],
            ['first_name' => 'Leakana', 'last_name' => 'Touch'],
            ['first_name' => 'Vitou', 'last_name' => 'Toung'],
            ['first_name' => 'Vathana', 'last_name' => 'Tout'],
            ['first_name' => 'Seakmey', 'last_name' => 'Try'],
            ['first_name' => 'Soklim', 'last_name' => 'Try'],
            ['first_name' => 'Davy', 'last_name' => 'Tung'],
            ['first_name' => 'Mouthe', 'last_name' => 'Ty'],
            // Skip 'Amaracaitly Uk' as it was in the original seed
            ['first_name' => 'Alisha', 'last_name' => 'Ung'],
            ['first_name' => 'Rotanak', 'last_name' => 'Ung'],
            ['first_name' => 'Sivkeang', 'last_name' => 'Uon'],
            ['first_name' => 'Yongye', 'last_name' => 'Uy'],
            ['first_name' => 'Chancola', 'last_name' => 'Vann'],
            ['first_name' => 'Sokhak Vachana', 'last_name' => 'Var'],
            ['first_name' => 'David', 'last_name' => 'Vicheth'],
            ['first_name' => 'Monopanha', 'last_name' => 'Vuthy'],
            ['first_name' => 'Kimleang', 'last_name' => 'Yam'],
            ['first_name' => 'Suycheu', 'last_name' => 'Yen'],
            ['first_name' => 'Chanmoni Sopheak', 'last_name' => 'Yeuon'],
            ['first_name' => 'Soungim', 'last_name' => 'Yi'],
            ['first_name' => 'Saparali Nishanbaevich', 'last_name' => 'Zhalalov'],
            ['first_name' => 'Yi An', 'last_name' => 'Zhou'],
        ];

        $existingEmailsCount = 0;
        $createdCount = 0;
        $phonePrefix = ['010', '011', '012', '015', '016', '017', '060', '061', '066', '067', '068', '069', '070', '077', '078', '089', '090', '092', '095', '096'];

        $this->command->info("Starting to add additional users...");
        $bar = $this->command->getOutput()->createProgressBar(count($users));
        $bar->start();

        foreach ($users as $userData) {
            $firstName = $userData['first_name'];
            $lastName = $userData['last_name'];
            $email = strtolower($firstName . $lastName . '@gmail.com');
            $email = str_replace(' ', '', $email); // Remove spaces from email

            // Check if user already exists
            $existingUser = User::where('email', $email)->first();
            
            if (!$existingUser) {
                User::create([
                    'first_name' => $firstName,
                    'last_name' => $lastName,
                    'email' => $email,
                    'password_hash' => Hash::make('11111111'),
                    'role' => 'user',
                    'is_active' => true,
                    'phone' => $phonePrefix[array_rand($phonePrefix)] . rand(100000, 999999), // Random phone number
                ]);
                $createdCount++;
            } else {
                $existingEmailsCount++;
            }
            $bar->advance();
        }

        $bar->finish();
        $this->command->newLine(2);
        $this->command->info("Created {$createdCount} new user accounts");
        $this->command->info("Skipped {$existingEmailsCount} existing email addresses");
    }
}
